-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 08:53:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

create database empresa_internet; 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_internet; 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_internet; 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8 ;
USE `empresa_internet` ;

-- -----------------------------------------------------
-- Table `empresa_internet.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `dataNascimento` DATETIME NOT NULL,
  `estado` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`Plano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`Plano` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`Plano` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `velocidade` INT NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `desconto` DECIMAL(8,2) NOT NULL,
  `Cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Plano_Cliente`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `mydb`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Plano_Cliente_idx` ON `empresa_internet`.`Plano` (`Cliente_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table attributes`empresa_internet`.`Cliente`
-- -----------------------------------------------------

INSERT INTO Cliente VALUES (1, 'Ana', 'da Silva', '1960-08-21', 'SP','Sao Paulo');
INSERT INTO Cliente VALUES (2, 'Pedro', 'Costa', '1980-05-12', 'SP','Sao Paulo');
INSERT INTO Cliente VALUES (3, 'Marcella', 'Oliveira', '1990-07-30', 'MG','Belo Horizonte');
INSERT INTO Cliente VALUES (4, 'Pamela', 'Pucinelli', '1999-04-11', 'RS','Blumenau'); 
INSERT INTO Cliente VALUES (5, 'Ana Carolina', 'Paccheco', '1995-04-23', 'SP','Campinas');
INSERT INTO Cliente VALUES (6, 'Andersson', 'Pierre', '1950-08-21', 'SP','Ribeirao Preto');
INSERT INTO Cliente VALUES (7, 'Suzanne', 'Savikias', '1979-09-21', 'RS','Floripa');
INSERT INTO Cliente VALUES (NULL, 'Joana Darc', 'Alencar', '1980-05-23', 'SP','Sao Paulo');
INSERT INTO Cliente VALUES (48,'Clare','George','1997-03-10','TG','Belgium');
INSERT INTO Cliente VALUES (45,'Rhiannon','Hebert','1996-09-23','KD','South Africa');

-- -----------------------------------------------------
-- Table attributes`empresa_internet`.`Plano`
-- -----------------------------------------------------

INSERT INTO Plano VALUES (30,'Kimberley',37,50.78,96,41);
INSERT INTO Plano VALUES (21,'Meghan',232,6.90,20,96);
INSERT INTO Plano VALUES (93,'Karyn',5,22.23,30,69);
INSERT INTO Plano VALUES (31,'Francis',170,7.80,26,76);
INSERT INTO Plano VALUES (99,'Olivia',109,97.99,73,85);
